version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: friendly-challenge
    versions:
    - 0.8.4
  - dependency-name: next-plausible
    versions:
    - 1.6.0
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.9
  - dependency-name: next
    versions:
    - 10.1.3
